# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

changesDir: .changes
unreleasedDir: unreleased
changelogPath: CHANGELOG.md
versionExt: md
versionFormat: '## {{.Version}} ({{.Time.Format "January 2, 2006"}})'
kindFormat: "{{.Kind}}:"
changeFormat: "* {{.Body}} {{- if .Custom.Issue }} ([#{{.Custom.Issue}}](https://github.com/hashicorp/terraform-exec/issues/{{.Custom.Issue}})){{- end}}"
custom:
    - key: Issue
      label: Issue/PR Number
      type: int
      minInt: 1
kinds:
    - label: ENHANCEMENTS
    - label: BUG FIXES
    - label: NOTES
    - label: UPGRADE NOTES
    - label: BREAKING CHANGES
newlines:
    afterChangelogHeader: 0
    afterReleaseNotes: 2
    beforeKind: 1
    afterKind: 1
    afterChange: 1
    afterVersion: 1
    beforeChangelogVersion: 0
    endOfVersion: 2
